pipeline {
  agent any

  environment {
    DOCKERHUB_REPO = "akrana2006"
  }

  stages {

    stage('Clone Code') {
      steps {
        git 'https://github.com/itsakrana/NotePad-Project.git'
      }
    }

    stage('Build Backend Image') {
      steps {
        sh 'docker build -t $DOCKERHUB_REPO/notes-backend ./backend'
      }
    }

    stage('Build Frontend Image') {
      steps {
        sh 'docker build -t $DOCKERHUB_REPO/notes-frontend ./frontend'
      }
    }

    stage('Login + Push Docker Images') {
      steps {
        withCredentials([usernamePassword(
          credentialsId: 'dockerhub-cred',
          usernameVariable: 'USER',
          passwordVariable: 'PASS'
        )]) {
          sh '''
            echo $PASS | docker login -u $USER --password-stdin

            docker push $DOCKERHUB_REPO/notes-backend
            docker push $DOCKERHUB_REPO/notes-frontend
          '''
        }
      }
    }

    stage('Deploy with Helm') {
      steps {
        sh '''
         export KUBECONFIG=/var/lib/jenkins/.kube/config

         helm upgrade --install mongodb ./helm/mongodb
         helm upgrade --install backend ./helm/backend
         helm upgrade --install frontend ./helm/frontend
        '''
      }
    }
  }
}
